### ISSUE TITLE
Upgrade Renovate OSS

### ISSUE THREAD

**Issue by fed89** [whitesource/renovate-on-prem#116]
Hello,

We are trying to use Renovate on-premise after using the CLI tool for a while. However when running it on the same project I have this message:
> File: `renovate.json`
Error type: The renovate configuration file contains some invalid settings
Message: `Invalid configuration option: dependencyDashboardTitle, Invalid configuration option: major.dependencyDashboardApproval`

Which is due to the Docker image using v21 after #96. Is it possible to release a new version upgrading the Renovate version to v22? Would be helpful given that the documentation for the previous release is no longer accessible and not sure how to fix the above.

Thanks

**Comment by rarkins** [comment]
Yes, a new release should happen this month. Re: the error you saw, please use `masterIssue` terminology for now.

**Comment by baurmatt** [comment]
Any update on this? We're looking for a Renovate Pro docker image which includes Renovate 23.29.0 as we'd like to have https://github.com/renovatebot/renovate/pull/7307. Thanks! :)

**Comment by rarkins** [comment]
Can you test out `whitesource/renovate:1.1.0-rc.0`? Draft release notes below:

This release updates Renovate OSS from v21.6.6 to v23.30.2.

Breaking changes:
 - `statusCheckVerify` is deprecated and removed
 - `lazyGrouping` is deprecated and removed

New package managers:
 - Python `setup.cfg`
 - helm: v3 support
 - jenkins: Add Jenkins plugin manager
 - yarn: v2 support

New config options:
- Configurable `prHeader` and `prFooter`
- Configurable `abortOnError` / `abortIgnoreStatusCodes` for custom hosts
- `repositoryCache` (experimental)
- host-rules: add support for disabling hosts
- Rename `masterIssue` to `dependencyDashboard`
- config: Added option `onboardingCommitMessage`
- config: Add support for `prBodyTemplate`
- New config option: `extractVersion`

Features for existing package managers:
- bazel: support http_file
- cargo: Add support for lockfile maintenance
- composer: lazy repository url
- nuget: look for refs within package.props schema
- pip: Hash updating
- pip: support env var interpolation
- sbt: Private variable version resolving
- sbt: Update scala version
- terraform: Add secondary release repo
- terraform: renovate `required_providers`
- terraform: Implement terraform helm chart update
- terraform: Implement terraform service discovery
- terraform: support docker provider
- terraform: support extended required_providers

Other:
- PR/MR edited notifications put in PR description instead of separate comment

**Comment by baurmatt** [comment]
Sure! :) I've upgraded our Dev System to 1.1.0-rc.0 and onboarded a Gitlab test repository. Everything looks good so far!

**Comment by rarkins** [comment]
Great. If anyone else can sanity check it then I'll promote it to officially released right away.

**Comment by enricojonas** [comment]
@rarkins Tested this as well, running GHE and maven project, working fine!

**Comment by rarkins** [comment]
Published [whitesource/renovate:1.1.0](https://github.com/whitesource/renovate-on-prem/releases/tag/1.1.0)
