### ISSUE TITLE
[Request] Please support `arm64` / `aarch64` docker image

### ISSUE THREAD

**Issue by darakena** [whitesource/renovate-on-prem#162]
Currently the docker image only run in the `amd64` architectures. Please support `arm64` too.

Thank you.

**Comment by rarkins** [comment]
This is not something currently planned, and not specific to this particular repository/distribution of Renovate. It would require e.g. https://github.com/renovatebot/internal-tools/issues/241 as well as https://github.com/renovatebot/renovate/issues/9229. Take particular note of https://github.com/renovatebot/renovate/issues/9229#issuecomment-803283791

Essentially, it would need someone with this requirement to step forward to be a long term maintainer of the "containerbase" tools we use to build Renovate, otherwise it is unlikely to be done.

If this associated issue in Renovate is ever implemented, this topic can be revisited here.
